name: Make Docs
on:
  push

env:
  DISCORD_TRADING_WEBHOOK: ${secrets.DISCORD_TRADING_WEBHOOK}
  ALPACA_SECRET_KEY: blank
  ALPACA_KEY_ID: blank

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        name: Set up caches
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pdoc
      - name: Build docs
        run: |
          pdoc ai-trading-bot -o docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.