name: push to docker


env:
  VERSION: v0.901

on:
  - workflow_dispatch

# on:
#   push:
#     branches: 
#       - master
#       - main
#     paths-ignore:
#       - '.github/workflows/**'
#     tags:        
#       - '*' # Push events to v1 tag

jobs:
    build-and-publish-latest:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master' # Running this job only for master branch

      steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.CR_PAT }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: lwarp_docker # Provide only Docker image name, tag will be automatically set to latest
          dockerfile: Dockerfile


    build-and-publish-tag:
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags/') # Running this job only for tags

      steps:
      - uses: actions/checkout@v2

      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.CR_PAT }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: lwarp_docker # Provide only Docker image name, tag will be automatically set to latest
          dockerfile: Dockerfile.full
          extract-git-tag: true  