name: Run Tests
on:
  push:
    branches:
      - master
      - main

env:
  DISCORD_TRADING_WEBHOOK: ${{ secrets.DISCORD_TRADING_WEBHOOK }}
  ALPACA_SECRET_KEY: blank
  ALPACA_KEY_ID: blank

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        name: Set up caches
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov

      - name: Coverage Report
        run: |
          python -m pytest --cov=./ --cov-report=xml --cov-fail-under=10

#       - name: Upload coverage to Codecov
#         uses: codecov/codecov-action@v1.0.15
#         with:
#           file: ./coverage.xml
#           flags: trading_ci
#           env_vars: PYTHON,OS
#           fail_ci_if_error: true
